### PR TITLE
Middleware

### PR DESCRIPTION
**Pull request by Luceium**
Support soft reroutes for protected routes

### CODE REVIEW

**Review by ray-sjsu — APPROVED** [review]
`MONGO_DB_KEY` and `VERCEL_URL` are unknown `.env` variables. Let people in the `.env` channel know what these variables should be.

**Review by luSteven01 — APPROVED** [review]
lgtm

**Review by ryanhtang — APPROVED** [review]
Looks good to me. But as raymund said send the updated .env file when ready

**Comment by Luceium** [comment]
I had based this branch on some of @KingSand08's work. I've now rebased the branch to only contain middleware related files.

**Pull request merged**
