### PR TITLE
Configure testing libraries and automated testing

### LINKED ISSUE #6: Set up Jest & Create demo tests

### LINKED ISSUE #19: Set up testing workflow
Set up github actions to protect breaking changes from being merged to main

### LINKED ISSUE #20: Set up code coverage workflow
Set up GitHub actions to set minimum values for code coverage

### PR DESCRIPTION
**Pull request by Luceium**
Set up directories and dependencies to use Jest and React Testing Library
Create example tests
Add GitHub Actions for code coverage & testing

Closes #1, closes #6, closes #20 , and closes #19

### CODE REVIEW

**Comment by Luceium** [comment]
@ahsan-ali26 @alia49 can you guys set up the testing directory and some demo tests before we submit this?
Also make sure that your tests run and pass.

**Review by ahsan-ali26 — COMMENTED** [review]
Looks good to push.

**Review by luSteven01 — APPROVED** [review]
lgtm

**Review by ray-sjsu — APPROVED** [review]
approved

**Pull request merged**
