### PR TITLE
Payment system

### PR DESCRIPTION
**Pull request by ryanhtang**
Integrated payment system. to get to the payment system and test add a /payment to the url. For testing payment cards please refer to the following link (scroll to the bottom): [https://docs.stripe.com/payments/accept-a-payment?platform=web&ui=elements](url)
Right now it is only set for base amount to be $100 per night and for one single night so the price is at 100 right now. Need to connect with booking system in order to make it dynamic.

### CODE REVIEW

**Comment by Luceium** [comment]
This is looking good. Please merge main in and request a review when ready. Don't wait to add more features, this PR is already too big and should be merged as soon as it's in a decent state.

**Review by ray-sjsu — APPROVED** [review]
Will approve as is. Integration with API will come later.

**Comment by ryanhtang** [comment]
> This is looking good. Please merge main in and request a review when ready. Don't wait to add more features, this PR is already too big and should be merged as soon as it's in a decent state.

Just merged it with main and should be up to date.  @Luceium if you want to review and approve/let me know if anything is wrong with the pr.

**Comment by ray-sjsu** [comment]
> > This is looking good. Please merge main in and request a review when ready. Don't wait to add more features, this PR is already too big and should be merged as soon as it's in a decent state.
> 
> Just merged it with main and should be up to date. @Luceium if you want to review and approve/let me know if anything is wrong with the pr.

I don't think this pull request was commited to `main`. Maybe try again?

**Review by Luceium — APPROVED** [review]
lgtm

**Pull request merged**
