### PR TITLE
Page structure 2.0

### PR DESCRIPTION
**Pull request by ray-sjsu**
Should have all the basic webpages needed for the entire project.

_Marketing_
`/` - advertising/landing page

_Reservations/Locations_
`locations` should have one main page that list all locations.
- `locations/[id]` slug to show one specific location.
`reservations`. Shows overview of all past and current reservations.

_User Auth_
`sign-in
`sign-up`

_User acocunt_
`profile`

_Rewards_
`rewards` - for our rewards system (Dedicated page to show redeemable rewards and progress)

Plan to reduce the number of slugs to reduce complexity and reduce number of pages. Also, to consolidate information into a few relevant pages instead of multiple pages.

### CODE REVIEW

**Review by KingSand08 — APPROVED** [review]

**Review by Luceium — CHANGES_REQUESTED** [review]
Please describe why you are adding some pages and removing others. The removed pages all seem vital.

**Comment by ray-sjsu** [comment]
@Luceium
I will discuss with frontend and talk to them about the revised page structure and why need some of these pages. We might update Figma accordingly.

**Comment by Luceium** [comment]
@ray-sjsu that sounds like a good course of action. Thank you.
I would like to focus on MMFs, blockers, and high priority items first.

**Comment by ray-sjsu** [comment]
@Luceium Update: [Figma - page structure](https://www.figma.com/design/Zc8Hhq42P4SMvJJoQIHlzj/Like-Home-(Copy)?node-id=3402-179&node-type=canvas&t=YBUI45XD0tubOPqO-0)

Waiting for feedback from frontend team.

**Comment by ray-sjsu** [comment]
#60

**Pull request closed without merging**
